# site settings
title: Huy Vo
subtitle: 
email: voxqhuy@gmail.com
description: At the moment, I'm sincerely looking for a job opportunity. <br />Please consider my info.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 4891 Taylor Circle
city: Collegedale
state: TN
zip_code: 37315
country: USA
phone: (650) 686-8241

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9

# social settings
500px_url:
facebook_url:
github_url: https://github.com/kohnewlife
gitlab_url: https://gitlab.com/voxqhuy
googleplus_url:
instagram_url: https://instagram.com/voxqhuy
linkedin_url: https://www.linkedin.com/in/voxqhuy
pinterest_url: https://www.pinterest.com/voxqhuy
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
